"""Resumable YouTube video upload using metadata generated by Gemini."""
from __future__ import annotations

import logging

from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

from app.config import settings
from app.youtube.auth import load_credentials

logger = logging.getLogger("chess64.youtube")


def upload_video(
    video_path: str,
    title: str,
    description: str,
    tags: list[str],
    thumbnail_path: str | None = None,
    privacy_status: str | None = None,
) -> str:
    """Uploads video_path with the given metadata. Returns the new video's URL."""
    creds = load_credentials()
    youtube = build("youtube", "v3", credentials=creds)

    body = {
        "snippet": {
            "title": title[:100],
            "description": description[:5000],
            "tags": tags[:500],
            "categoryId": settings.youtube_category_id,
        },
        "status": {
            "privacyStatus": privacy_status or settings.youtube_default_privacy,
            "selfDeclaredMadeForKids": False,
        },
    }

    media = MediaFileUpload(video_path, chunksize=-1, resumable=True, mimetype="video/mp4")
    request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            logger.info("Upload progress: %d%%", int(status.progress() * 100))

    video_id = response["id"]

    if thumbnail_path:
        try:
            youtube.thumbnails().set(
                videoId=video_id, media_body=MediaFileUpload(thumbnail_path)
            ).execute()
        except Exception as exc:
            logger.warning("Thumbnail upload failed (video still published): %s", exc)

    return f"https://youtu.be/{video_id}"
